origin:
  file:
    import: /mnt/00D4D3AFD4D3A566/Projetos/Desafios/Files
    export: /mnt/00D4D3AFD4D3A566/Projetos/Desafios/Files/out

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379